//! build.rs v3.0 — 编译时代码生成器
//!
//! 输出两个文件:
//!   1. doctypes.rs   — Rust 结构体 (类型安全, 零运行时开销)
//!   2. doctype_meta.rs — 字段元数据 (标签/类型/选项, 供 API / 前端动态表单使用)
//!
//! 两阶段扫描:
//!   1. 扫描 erpnext + frappe 所有 doctype JSON，建立索引
//!   2. 生成 Rust 结构体 + 元数据注册表

use std::collections::{HashMap, HashSet};
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=/home/cyborg/erpnext/");
    println!("cargo:rerun-if-changed=/home/cyborg/frappe/");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var("OUT_DIR").unwrap();
    let structs_path = Path::new(&out_dir).join("doctypes.rs");
    let meta_path = Path::new(&out_dir).join("doctype_meta.rs");

    // ── Phase 1: 扫描 ──
    let search_paths = ["/home/cyborg/erpnext/erpnext", "/home/cyborg/frappe/frappe"];
    let mut all_doctypes: Vec<DoctypeInfo> = Vec::new();
    let mut known_names: HashSet<String> = HashSet::new();

    for base in &search_paths {
        let base_path = Path::new(base);
        if base_path.exists() {
            scan_doctypes(base_path, &mut all_doctypes, &mut known_names);
        }
    }

    eprintln!("cargo:warning=Found {} doctypes", all_doctypes.len());

    // Collect is_table for lookup
    let is_table: HashMap<String, bool> = all_doctypes
        .iter()
        .map(|d| (d.name.clone(), d.is_table))
        .collect();

    // ── Phase 2: 生成结构体 + 元数据 ──
    let mut structs = String::new();
    structs.push_str("// AUTO-GENERATED by build.rs v3.0 — doctype structs\n// DO NOT EDIT\n\n");
    structs.push_str("use serde::{Serialize, Deserialize};\n");
    structs.push_str("use chrono::NaiveDate;\n");
    structs.push_str("use rust_decimal::Decimal;\n\n");

    let mut meta_code = String::new();
    meta_code.push_str("// AUTO-GENERATED by build.rs v3.0 — doctype field metadata\n// DO NOT EDIT\n\n");
    meta_code.push_str("/// 字段元数据\n");
    meta_code.push_str("#[derive(Debug, Clone)]\n");
    meta_code.push_str("pub struct FieldMeta {\n");
    meta_code.push_str("    pub fieldname: &'static str,\n");
    meta_code.push_str("    pub label: &'static str,\n");
    meta_code.push_str("    pub fieldtype: &'static str,\n");
    meta_code.push_str("    pub options: &'static str,\n");
    meta_code.push_str("    pub required: bool,\n");
    meta_code.push_str("    pub default_value: &'static str,\n");
    meta_code.push_str("}\n\n");

    meta_code.push_str("/// 文档类型元数据\n");
    meta_code.push_str("#[derive(Debug, Clone)]\n");
    meta_code.push_str("pub struct DoctypeMeta {\n");
    meta_code.push_str("    pub name: &'static str,\n");
    meta_code.push_str("    pub is_single: bool,\n");
    meta_code.push_str("    pub is_table: bool,\n");
    meta_code.push_str("    pub autoname: &'static str,\n");
    meta_code.push_str("    pub fields: &'static [FieldMeta],\n");
    meta_code.push_str("}\n\n");

    // Generate per-doctype field arrays
    let mut meta_blocks: Vec<String> = Vec::new();
    let mut match_arms: Vec<String> = Vec::new();

    for dt in &all_doctypes {
        // -- Struct generation --
        let code = generate_struct(dt, &is_table);
        structs.push_str(&code);
        structs.push('\n');

        // -- Meta generation --
        let (meta_block, arm) = generate_meta_for_doctype(dt);
        if !meta_block.is_empty() {
            meta_blocks.push(meta_block);
            match_arms.push(arm);
        }
    }

    structs.push_str(&format!("// {} doctypes generated\n", all_doctypes.len()));
    fs::write(&structs_path, &structs).unwrap();

    // Write meta: field arrays + match function
    meta_code.push_str(&meta_blocks.join("\n"));
    meta_code.push_str("\npub fn get_doctype_meta(name: &str) -> Option<&'static DoctypeMeta> {\n");
    meta_code.push_str("    match name {\n");
    meta_code.push_str(&match_arms.join("\n"));
    meta_code.push_str("\n        _ => None,\n");
    meta_code.push_str("    }\n");
    meta_code.push_str("}\n\n");

    meta_code.push_str(&format!(
        "/// 所有已注册的 doctype 名称\npub static ALL_DOCTYPES: &[&str] = &[{}];\n",
        all_doctypes
            .iter()
            .map(|d| format!("\"{}\"", d.name))
            .collect::<Vec<_>>()
            .join(", ")
    ));

    fs::write(&meta_path, &meta_code).unwrap();

    eprintln!(
        "cargo:warning=Generated {} structs + {} meta entries",
        all_doctypes.len(),
        meta_blocks.len()
    );
}

// ── Data structures ──

struct DoctypeInfo {
    name: String,
    json_path: String,
    is_single: bool,
    is_table: bool,
    autoname: String,
}

// ── Scanner ──

fn scan_doctypes(base: &Path, all: &mut Vec<DoctypeInfo>, known: &mut HashSet<String>) {
    if let Ok(modules) = fs::read_dir(base) {
        for module in modules.flatten() {
            let module_path = module.path();
            if !module_path.is_dir() { continue; }
            let doctype_dir = module_path.join("doctype");
            if !doctype_dir.exists() { continue; }
            if let Ok(entries) = fs::read_dir(&doctype_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if !path.is_dir() { continue; }
                    let dirname = path.file_name().unwrap().to_string_lossy();
                    let json_file = path.join(format!("{}.json", dirname));
                    if !json_file.exists() { continue; }

                    let content = match fs::read_to_string(&json_file) {
                        Ok(c) => c,
                        Err(_) => continue,
                    };
                    let dt: serde_json::Value = match serde_json::from_str(&content) {
                        Ok(v) => v,
                        Err(_) => continue,
                    };

                    let name = dt["name"].as_str().unwrap_or(&dirname).to_string();
                    if name.is_empty() || known.contains(&name) { continue; }
                    known.insert(name.clone());
                    all.push(DoctypeInfo {
                        name,
                        json_path: json_file.to_string_lossy().to_string(),
                        is_single: dt["issingle"].as_i64().unwrap_or(0) == 1,
                        is_table: dt["istable"].as_i64().unwrap_or(0) == 1,
                        autoname: dt["autoname"].as_str().unwrap_or("").to_string(),
                    });
                }
            }
        }
    }
}

// ── Constants ──

const LAYOUT_TYPES: &[&str] = &[
    "Section Break", "Column Break", "Tab Break", "HTML", "Image",
    "Button", "Heading", "Fold", "Read Only",
];

const RUST_KEYWORDS: &[&str] = &[
    "type", "match", "loop", "move", "crate", "self", "super", "extern", "mod", "use", "where",
    "async", "await", "dyn", "impl", "trait", "enum", "struct", "fn", "let", "mut", "ref",
    "static", "const", "in", "for", "while", "if", "else", "return", "break", "continue",
    "true", "false", "box", "abstract", "become", "do", "final", "macro", "override", "priv",
    "typeof", "unsized", "virtual", "yield", "union",
];

fn is_layout_field(ftype: &str) -> bool { LAYOUT_TYPES.contains(&ftype) }

fn sanitize_ident(s: &str) -> String {
    let name = s.replace('-', "_").replace(' ', "_").to_lowercase();
    if RUST_KEYWORDS.contains(&name.as_str()) { format!("r#{}", name) }
    else if name.is_empty() { "unknown_field".to_string() }
    else { name }
}

fn to_pascal_case(s: &str) -> String {
    s.split(&[' ', '-', '_'][..])
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn map_fieldtype(ftype: &str) -> &'static str {
    match ftype {
        "Link" | "Dynamic Link" | "Select" | "Data" | "Text" | "Small Text" | "Long Text"
        | "Code" | "HTML Editor" | "Markdown Editor" | "Password" | "Attach" | "Attach Image"
        | "Color" | "Time" | "Date of Birth" | "Date of Joining"
        | "Phone" | "Email" | "URL" | "Barcode" | "Geolocation" | "Signature"
        | "Table MultiSelect" => "String",
        "Int" | "Duration" => "i64",
        "Check" => "i32",
        "Float" | "Currency" | "Percent" => "Decimal",
        "Date" => "Option<NaiveDate>",
        "Datetime" => "Option<chrono::NaiveDateTime>",
        _ => "String",
    }
}

// ── Struct generator ──

fn generate_struct(dt: &DoctypeInfo, is_table_map: &HashMap<String, bool>) -> String {
    let content = match fs::read_to_string(&dt.json_path) { Ok(c) => c, Err(_) => return String::new() };
    let doctype: serde_json::Value = match serde_json::from_str(&content) { Ok(v) => v, Err(_) => return String::new() };

    let struct_name = to_pascal_case(&dt.name);
    let table_name = format!("tab{}", dt.name);
    let mut code = String::new();

    code.push_str(&format!("/// {}\n", dt.name));

    if dt.is_table {
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        code.push_str("#[serde(rename_all = \"snake_case\")]\n");
    } else {
        code.push_str("#[derive(Debug, Clone, Serialize, Deserialize, frappe_core::Doctype)]\n");
    }

    code.push_str(&format!("#[doctype(name = \"{}\", table = \"{}\"", dt.name, table_name));
    if dt.is_single { code.push_str(", single"); }
    if !dt.autoname.is_empty() { code.push_str(&format!(", autoname = \"{}\"", dt.autoname)); }
    code.push_str(")]\n");
    code.push_str(&format!("pub struct {} {{\n", struct_name));

    // Core fields
    code.push_str("    #[doctype(field = \"name\", primary_key)]\n    #[serde(default)]\n    pub name: String,\n\n");
    if !dt.is_table {
        code.push_str("    #[doctype(field = \"docstatus\", default = 0)]\n    #[serde(default)]\n    pub docstatus: i32,\n\n");
    } else {
        for f in &["parent", "parentfield", "parenttype", "idx"] {
            let ty = if *f == "idx" { "i32" } else { "String" };
            code.push_str(&format!("    #[doctype(field = \"{}\")]\n    #[serde(default)]\n    pub {}: {},\n\n", f, f, ty));
        }
    }

    if let Some(fields) = doctype["fields"].as_array() {
        for field in fields {
            let fieldname = field["fieldname"].as_str().unwrap_or("");
            let fieldtype = field["fieldtype"].as_str().unwrap_or("Data");
            if fieldname.is_empty() || is_layout_field(fieldtype)
                || fieldname == "name" || fieldname == "docstatus"
                || (dt.is_table && ["parent","parentfield","parenttype","idx"].contains(&fieldname))
            { continue; }

            let ident = sanitize_ident(fieldname);
            let required = field["reqd"].as_i64().unwrap_or(0) == 1;
            let options = field["options"].as_str().unwrap_or("");
            let label = field["label"].as_str().unwrap_or(fieldname);

            let rust_type = if fieldtype == "Table" {
                if options.is_empty() { "String".to_string() }
                else { format!("Vec<{}>", to_pascal_case(options)) }
            } else { map_fieldtype(fieldtype).to_string() };

            code.push_str(&format!("    #[doctype(field = \"{}\"", fieldname));
            if required { code.push_str(", required"); }
            if fieldtype == "Link" && !options.is_empty() { code.push_str(&format!(", link = \"{}\"", options)); }
            code.push_str(&format!(", label = \"{}\")]\n", label));
            code.push_str("    #[serde(default)]\n");
            code.push_str(&format!("    pub {}: {},\n\n", ident, rust_type));
        }
    }

    code.push_str("}\n");
    code
}

// ── Meta generator ──

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn generate_meta_for_doctype(dt: &DoctypeInfo) -> (String, String) {
    let content = match fs::read_to_string(&dt.json_path) { Ok(c) => c, Err(_) => return (String::new(), String::new()) };
    let doctype: serde_json::Value = match serde_json::from_str(&content) { Ok(v) => v, Err(_) => return (String::new(), String::new()) };

    let safe_name = sanitize_ident(&dt.name);
    let array_name = format!("META_FIELDS_{}", safe_name.to_uppercase());

    let mut field_entries: Vec<String> = Vec::new();
    if let Some(fields) = doctype["fields"].as_array() {
        for field in fields {
            let fieldname = field["fieldname"].as_str().unwrap_or("");
            let fieldtype = field["fieldtype"].as_str().unwrap_or("Data");
            if fieldname.is_empty() || fieldname == "name" { continue; }
            // 只跳过纯布局字段（Column Break, HTML, Button 等），保留 Section Break / Tab Break 用于前端分组
            if fieldtype == "Column Break" || fieldtype == "HTML" || fieldtype == "Button"
                || fieldtype == "Image" || fieldtype == "Heading" || fieldtype == "Fold"
                || fieldtype == "Read Only" { continue; }

            let label = escape_rust_str(field["label"].as_str().unwrap_or(fieldname));
            let options = escape_rust_str(field["options"].as_str().unwrap_or(""));
            let required = field["reqd"].as_i64().unwrap_or(0) == 1;
            let default = escape_rust_str(field["default"].as_str().unwrap_or(""));

            field_entries.push(format!(
                "    FieldMeta {{ fieldname: \"{}\", label: \"{}\", fieldtype: \"{}\", options: \"{}\", required: {}, default_value: \"{}\" }}",
                fieldname, label, fieldtype, options, required, default
            ));
        }
    }

    if field_entries.is_empty() { return (String::new(), String::new()); }

    let array_code = format!(
        "static {}: &[FieldMeta] = &[\n{}\n];\n\nstatic META_{}: DoctypeMeta = DoctypeMeta {{\n    name: \"{}\",\n    is_single: {},\n    is_table: {},\n    autoname: \"{}\",\n    fields: {},\n}};\n",
        array_name, field_entries.join(",\n"),
        safe_name.to_uppercase(),
        escape_rust_str(&dt.name),
        dt.is_single, dt.is_table,
        escape_rust_str(&dt.autoname),
        array_name
    );

    let match_arm = format!(
        "        \"{}\" => Some(&META_{}),",
        escape_rust_str(&dt.name), safe_name.to_uppercase()
    );

    (array_code, match_arm)
}
